### ISSUE TITLE
Voice Over product details/checkout 

### ISSUE THREAD

**Issue by Sebby-T** [KyleVBP/ecommerce-pattern-library#8]
The site looks awesome, good work!

The header and footer need aria labels to describe where they would bring the user.

Product details section does not currently read out the product content, so the user would not know what they are purchasing or viewing. The button read fine.

There is no current or obvious way to reach the checkout form page. Your form fields don't read out the labels they are in except for the first one. The user would not know which field they are in, or what to enter for information. Make sure the fields are associated with each other. The "for" and "id" attributes should match and be unique for each field.

**Comment by KyleVBP** [comment]
Fixed skip links and form voiceover
