### ISSUE TITLE
Accessibility testing - Sim Daltonism

### ISSUE THREAD

**Issue by karenhodgkinson** [KyleVBP/ecommerce-pattern-library#9]
Your nav buttons can be hard to tell the difference between inactive vs hover/active states (see screenshots 1-2). Your headings can be hard to read against your background colour for people with certain types of colour blindness (see screenshots 3-4).

<img width="309" alt="1" src="https://user-images.githubusercontent.com/31959335/56229630-5c106180-6048-11e9-84fe-76e9435045f3.png">
<img width="319" alt="2" src="https://user-images.githubusercontent.com/31959335/56229631-5c106180-6048-11e9-9df4-97db81a9b6db.png">
<img width="342" alt="3" src="https://user-images.githubusercontent.com/31959335/56229632-5c106180-6048-11e9-87e6-adf55192c138.png">
<img width="515" alt="4" src="https://user-images.githubusercontent.com/31959335/56229633-5c106180-6048-11e9-9a99-fbfd4059c4ac.png">

**Comment by KyleVBP** [comment]
Font colours where changed to increase readability
